#!/usr/bin/env python3
"""Compare output of the C and Python nanopb generators.

For each test proto:
1. Compile to .pb with grpcio-tools protoc
2. Run Python generator -> python_{name}.pb.{h,c}
3. Run C generator      -> c_{name}.pb.{h,c}
4. Normalize both and diff; fail if they differ
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
import shutil


def normalize(text):
    """Normalize generated file content for comparison.

    Strips/normalizes things that differ between generators for non-functional reasons:
    - Comment-only lines (/* ... */ single-line)
    - Trailing whitespace on each line
    - Multiple blank lines -> one blank line
    - Column alignment in #define (variable padding)
    """
    lines = text.splitlines()
    out = []
    prev_blank = False
    for line in lines:
        # Strip trailing whitespace
        line = line.rstrip()
        # Drop preamble comment lines (/* Automatically generated ... */ and /* Generated by ... */)
        if re.match(r'/\*\s*(Automatically generated|Generated by)', line):
            continue
        # Collapse multiple spaces inside #define lines for alignment-insensitive comparison
        # e.g.  "#define Foo_size      42" -> "#define Foo_size 42"
        if line.startswith('#define '):
            line = re.sub(r'\s{2,}', ' ', line)
        # Track blank lines
        is_blank = (line == '')
        if is_blank and prev_blank:
            continue
        prev_blank = is_blank
        out.append(line)
    return '\n'.join(out)


def run(cmd, cwd, check=True):
    """Run a command, return (returncode, stdout, stderr)."""
    result = subprocess.run(
        cmd, cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    if check and result.returncode != 0:
        print(f"Command failed: {' '.join(str(c) for c in cmd)}", file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    return result


def main():
    parser = argparse.ArgumentParser(description='Compare nanopb generator outputs')
    parser.add_argument('--proto',        required=True, help='Input .proto file')
    parser.add_argument('--c-generator',  required=True, help='Path to nanopb-generator-c binary')
    parser.add_argument('--py-generator', required=True, help='Path to nanopb_generator.py')
    parser.add_argument('--work-dir',     default=None,  help='Working directory (default: tmp)')
    args = parser.parse_args()

    proto_path = os.path.abspath(args.proto)
    proto_dir  = os.path.dirname(proto_path)
    proto_name = os.path.basename(proto_path)           # e.g. simple.proto
    proto_base = os.path.splitext(proto_name)[0]        # e.g. simple
    c_gen      = os.path.abspath(args.c_generator)
    py_gen     = os.path.abspath(args.py_generator)

    work_dir = args.work_dir
    cleanup  = False
    if work_dir is None:
        work_dir = tempfile.mkdtemp(prefix='nanopb_compare_')
        cleanup = True
    else:
        os.makedirs(work_dir, exist_ok=True)

    try:
        _run_test(proto_path, proto_dir, proto_name, proto_base, c_gen, py_gen, work_dir)
    finally:
        if cleanup:
            shutil.rmtree(work_dir, ignore_errors=True)


def _run_test(proto_path, proto_dir, proto_name, proto_base, c_gen, py_gen, work_dir):
    pb_file = os.path.join(work_dir, proto_base + '.pb')

    # --- Step 1: compile .proto → .pb ---
    print(f"[1] Compiling {proto_name} → {proto_base}.pb")
    run([
        sys.executable, '-m', 'grpc_tools.protoc',
        f'-I{proto_dir}',
        f'--descriptor_set_out={pb_file}',
        '--include_imports',
        proto_name
    ], cwd=proto_dir)

    # Also copy .options file if present
    opt_src = os.path.splitext(proto_path)[0] + '.options'
    if os.path.exists(opt_src):
        shutil.copy(opt_src, work_dir)

    # --- Step 2: Python generator ---
    py_dir = os.path.join(work_dir, 'py')
    os.makedirs(py_dir, exist_ok=True)
    if os.path.exists(opt_src):
        shutil.copy(opt_src, py_dir)

    print(f"[2] Running Python generator on {proto_base}.pb")
    run([
        sys.executable, py_gen,
        '-D', py_dir,
        pb_file
    ], cwd=work_dir)

    py_h = os.path.join(py_dir, proto_base + '.pb.h')
    py_c = os.path.join(py_dir, proto_base + '.pb.c')

    # --- Step 3: C generator ---
    c_dir = os.path.join(work_dir, 'c')
    os.makedirs(c_dir, exist_ok=True)
    if os.path.exists(opt_src):
        shutil.copy(opt_src, c_dir)

    print(f"[3] Running C generator on {proto_base}.pb")
    run([
        c_gen,
        '-D', c_dir,
        pb_file
    ], cwd=work_dir)

    c_h = os.path.join(c_dir, proto_base + '.pb.h')
    c_c = os.path.join(c_dir, proto_base + '.pb.c')

    # --- Step 4: Diff ---
    failed = False
    for (label, py_f, c_f) in [('.pb.h', py_h, c_h), ('.pb.c', py_c, c_c)]:
        if not os.path.exists(py_f):
            print(f"FAIL: Python generator did not produce {py_f}", file=sys.stderr)
            failed = True
            continue
        if not os.path.exists(c_f):
            print(f"FAIL: C generator did not produce {c_f}", file=sys.stderr)
            failed = True
            continue

        py_text = normalize(open(py_f).read())
        c_text  = normalize(open(c_f).read())

        if py_text == c_text:
            print(f"  OK  {label}")
        else:
            print(f"  FAIL {label} — outputs differ:")
            # Print a simple diff
            import difflib
            py_lines = py_text.splitlines(keepends=True)
            c_lines  = c_text.splitlines(keepends=True)
            diff = list(difflib.unified_diff(py_lines, c_lines,
                                             fromfile=f'python/{proto_base}{label}',
                                             tofile=f'c/{proto_base}{label}'))
            for d in diff[:80]:
                sys.stdout.write(d)
            if len(diff) > 80:
                print(f"  ... ({len(diff) - 80} more lines)")
            failed = True

    if failed:
        sys.exit(1)
    print("PASS")


if __name__ == '__main__':
    main()
